# Generated by Django 5.0.6 on 2024-06-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': False},
        ),
    ]
